### ISSUE TITLE
Floating meteors

### ISSUE THREAD

**Issue by PavanLuca** [LoneWolfHT/torrlund#6]
When a meteor crash, it floats over the impact node. It falls again once hit by hammer though.

**Comment by LoneWolfHT** [comment]
Fixed in upcoming update

**Comment by PavanLuca** [comment]
If it still happens it means that the hole wasn't created because the map chunk wasn't yet loaded?
![Schermata da 2024-03-07 17-02-19](https://github.com/LoneWolfHT/torrlund/assets/123581658/2413be0a-7508-4c6f-9bfa-1eda97974ec7)

**Comment by LoneWolfHT** [comment]
Huh, probably
